### ISSUE TITLE
Following Readme instructions generates error

### ISSUE THREAD

**Issue by jnowland** [johannesjo/generator-angular-auto-admin-loopback#2]
When attempting to login I'm getting the following error after following the `readme.md`
https://docs.angularjs.org/error/$injector:unpr?p0=UserProvider%20%3C-%20User%20%3C-%20Auth

**Comment by johannesjo** [comment]
Which one of the instructions do you mean? 'manually building a new app' or the ones for 'adding it to your existing angular frontend'?

You need to make sure to include the files for aaal.
