### ISSUE TITLE
Issue when executing "yo aaal" command with mysql loopback:model

### ISSUE THREAD

**Issue by mirandole** [johannesjo/generator-angular-auto-admin-loopback#3]
Hi !

I'm trying to use generator angular auto admin loopback and everything works fine when I install it with a loopback:model on memory but it doesn't work when I'm using a loopback:model on my mysql db.

The loopback explorer gets the data from the mysql db successfully. But I got this issue when I do this command : 
`yo aaal`

The script can't finish. It displays this on my prompt : 
`....
injecting state into app/scripts/aaal/aaal-routes.js
 updating aaal-routes.js
Chargement de l'application LoopBack "/Users/xxxx/NodeProjects/strongloop/crud-loop/server/server.js"
Génération de "lbServices" pour le noeud final d'API "/api"
Warning: scope User.accessTokens targets class "AccessToken", which is not exposed 
via remoting. The Angular code for this scope won't be generated.
Sauvegarde de la source des services générés vers "/Users/xxxx/NodeProjects/strongloop/crud-loop/client/app/scripts/aaal/global-services/lb-services-s.js"`

I've tried again with a fresh install. If I don't use a loopback model connected to mysql, I have no issue. The script finished well displaying the same prompt message 

`injecting state into app/scripts/aaal/aaal-routes.js
 updating aaal-routes.js
Chargement de l'application LoopBack "/Users/xxxx/NodeProjects/strongloop/crud-loop/server/server.js"
Génération de "lbServices" pour le noeud final d'API "/api"
Warning: scope User.accessTokens targets class "AccessToken", which is not exposed 
via remoting. The Angular code for this scope won't be generated.
Sauvegarde de la source des services générés vers "/Users/xxxx/NodeProjects/strongloop/crud-loop/client/app/scripts/aaal/global-services/lb-services-s.js"
`

The script can't finished after I have done this : 
`slc loopback:datasource mydatabase`

I would be very thankful if you can help me.
Best regards

**Comment by johannesjo** [comment]
Thank you very much for reporting. I'll try to look closer into it this Friday. But this looks more like something related to loopback and its lbServices generator script. Are you using the most recent version of loopback?

**Comment by mirandole** [comment]
Hi Johannes !

Thank you so much for your answer. 

I'm using this version of strongloop : 

slc -v : 
strongloop v6.0.3 (node v6.1.0)
├── strong-arc@1.8.9 (3dd25ac)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.3
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.1.0 (1767f27)
├── generator-loopback@1.24.4 (0c6b9c3)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

It seems to be the latest version.

I've attached a .txt copy of my lbServices generator script to this post. If you need to look at it.
[lb-ng.txt](https://github.com/johannesjo/generator-angular-auto-admin-loopback/files/577532/lb-ng.txt)

Everything works fine until I install `loopback-connector-mysql@^2.2`. In that case when I do `yo aaal` to update the generator with my new mysql model, the script can't finished.
I have the same issue with `loopback-connector-mongodb`
It works when I use memory datasource only for now.

I have tried to manually generate services with `lb-ng server/server.js client/app/scripts/aaal/global-services/ls-ervices.js`
The script can't finished too. So it seems that the issue doesn't come from your works. 

Does it work with the loopback-connector mysql or mongodb on your computer ?

Best regards,

**Comment by johannesjo** [comment]
No there are no errors for me even when hooking the mysql-connector. You'll probably want to report this to the loopback creators.

**Comment by mirandole** [comment]
It seems to work better using your `angular-auto-admin-loopback` on my local mac OS X computer. I'm able to connect to mysql database and get the data on the crud. Unfortunately, I can't delete any row of data from your CRUD yet. 

I've tried `angular-auto-admin-loopback` on another fresh ubuntu server. Everything works well. 
There is probably something missing on my Mac.

**Comment by mirandole** [comment]
I've uninstall and reinstall node. Everything seems to work well on my Mac now.
Sorry for the inconvenience.

Best regards,

**Comment by mirandole** [comment]
I've reinstalled node and everything worked well. I've used yo yaaa generator to add a new data model and I have some issues again. The delete button doesn't work anymore and the edit page seems broken on both systems Ubuntu 14.04 and MAC OS X 
![capture d ecran 2016-11-08 a 15 24 56](https://cloud.githubusercontent.com/assets/7462919/20102758/8ed20080-a5c7-11e6-8aec-051680c4b5b9.png)

The some files are different inside client/app/scripts/aaal from the original files of `angular-auto-admin-loopback` example after doing `yo aaal` command.
I think this is why it doesn't work. I may not have the latest version of aaal.

**Comment by johannesjo** [comment]
Does your console show any errors? I mean the JavaScript console in the browser?

**Comment by mirandole** [comment]
No. There is nothing written on the chrome inspector console when I click on the delete button and nothing happens on the webpage.
I will use the basic templates of code of `angular-auto-admin-looopback` to get it work with my database model. I can't use `yo aaal`.

After executing `yo aaal`
the toys-edit-c.html file looks like this : 

```
<div class="page--toys-overview">
    <button type="button"
            ui-sref="private.ToysEdit"
            class="btn btn-success">
        <i class="glyphicon glyphicon-plus">
        </i> Add new item
    </button>

    <aaal-overview-table columns="vm.columns"
                         rows="vm.rowCollection"
                         delete-fn="vm.removeItem"
                         view-state-link="{{ vm.viewState }}"
                         edit-state-link="{{ vm.editState }}"></aaal-overview-table>
</div>
```

It's different than the default toys-edit-c.html I got after clone git angular-auto-admin-looopback repos.

**Comment by johannesjo** [comment]
That's weird. The screenshot you posted looks like angular isn't loaded at all. The template looks correct. The files being different is how it should be. After all they're generated from your models. In fact there shouldn't be a `toys-edit-c.html` before you run the generator once.

**Comment by johannesjo** [comment]
I digged deeper into the issue. If your model name is lowercase you probably want to change the following lines in your `toys-edit-c.js`

```
 vm.modelName = 'toys';
 //form and schema definition
 vm.schema = aaalToSchemaForm('toys');
```

I'll will release a new version with a fix for this issue.

**Comment by mirandole** [comment]
I apologize I've probably misspoken. I have executed `yo aaal` command after adding a new `loopback:model`  inside a clone of this repository [angular-auto-admin-looopback](https://github.com/johannesjo/angular-auto-admin-looopback). This is why I still have AnotherModel, Beer, TestModel and Toys. I've kept default models. So when I have executed `yo aaal` after deleted aaal folder, it has generated again front end files from these models.

**Comment by johannesjo** [comment]
@mirandole yes this is correct. Does it work for you, when you update the generator with the latest version?

**Comment by mirandole** [comment]
Hi @johannesjo !

I have done these commands : 
`sudo npm update -g generator-aaal`
`cd client`
`rm -r app/scripts/aaal/`
`yo aaal`

then run node and gulp and been to the admin webpage.

I can now have access to my shop model. I can add new item and edit an item. But the delete button still doesn't work.

**Comment by johannesjo** [comment]
Thanks again for reporting. I made a new release of aaal where things should work out. Can you please check again?

**Comment by mirandole** [comment]
Everything works fine now. Thank you very much.

**Comment by mirandole** [comment]
You project is very good. I was wondering if you think to add more functionalities ? 

1) It will be nice to be able to automatically generate column names of the table.

2) To use loopback relations might be very useful too. 
I mean if you have a list of contacts and a list of companies. Each contact belongs to a company. The relation is done with the companyId registered in the contact row. And the name of the company are registered on the company row. It might be cool to get the company name from the companyId and display it on the contact list. 

I'll try to implement this on your code. But it won't be automated. I'm a bit new to Node JS and Angular JS but I need to do this to train myself.
So I'll try to do this :). Don't know if you think to implement this functionality too.

**Comment by johannesjo** [comment]
I'm glad that you like the generator :) 

I intend to expand the functionality by quite a bit, but unfortunately I don't know when I will have the time for this. Currently I've no practical need for it, but I hope this will change though it definitely won't before the end of the year. There was also the idea [integrate this](https://github.com/beeman/loopback-angular-admin/issues/171) with the  [loopback-angular-admin](https://github.com/beeman/loopback-angular-admin) but there isn't much progress on that one neither.
