### ISSUE TITLE
[HELP] Yo moda command does not work for loopback app on windows machine

### ISSUE THREAD

**Issue by KratiChauhan** [johannesjo/generator-angular-auto-admin-loopback#4]
Hello 

When i follow your instructions for manually building a new app, on step 3 when i run yo moda [nameofapp], I does nothing and there is no error as well. Attaching screenshot for reference. 
please let me know how to proceed further by helping me resolve this issue.

![image](https://cloud.githubusercontent.com/assets/23445940/20558351/9a7c1004-b195-11e6-87db-c700c145178e.png)

**Comment by johannesjo** [comment]
There is probably no echo command on Windows. You need to create a .yo-rc.json file in the client sub folder with nothing but `{}` in it. I hope this helps. Node on Windows is not working nicely sometimes..

**Comment by KratiChauhan** [comment]
the .yo-rc.json is created with {} ..but it is the yo moda command which is not running. 
However to test it i simply created a new blank folder and tried the yo moda command, it worked well but not when i try it in my loopback app folder

**Comment by johannesjo** [comment]
That's weird. Unfortunately I don't have a Windows System I can test this on properly, but could you maybe try two things for me:
1. Copy the contents of the .yo-rc.json of the installation where it worked to the loopback/client folder and try again.
2. Try deleting the .yo-rc.json in the loopback (not the client folder) folder  and try again.

**Comment by KratiChauhan** [comment]
Hi

I did try the steps suggested by you, find below the results 

1. Did copy the contents of the .yo-rc.json to loopback/client folder and yo moda command **did work**
2.  Did **not work** when i delete the .yo-rc.json from loopback folder while keeping the .yo-rc.json file in client folder with just "{}"

**Comment by johannesjo** [comment]
@KratiChauhan Thank you very much for reporting back. I'm glad that it works for you. This actually seems to be some issue with yeoman (+windows) itself. As there are not too many windows users I would leave it at this work around for now, but of course feel free to report to them.
